baseURL: https://blog.project-trans.org
title: Project Trans 非正式笔记
theme: mtfwiki-blog
copyright: '&copy; $YEAR$ Project Trans'

hasCJKLanguage: true
defaultContentLanguage: zh-CN
disableKinds: [taxonomy, term, RSS]
enableRobotsTXT: true

params:
  description: Project Trans 非正式笔记
  twitter: MtFwiki
  telegram: MtFwiki
  author:
    name: Project Trans
    url: https://project-trans.org
    email: admin@project-trans.org
  googleAnalytics:
    ID: 'G-DVB8ZD276Q'

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true

languages:
  zh-CN:
    languageCode: zh-CN
    languageName: Chinese
    weight: 1
