baseURL: https://blog.project-trans.org
title: Project Trans 非正式笔记
theme: mtfwiki-blog
copyright: '&copy; $YEAR$ Project Trans'

hasCJKLanguage: true
defaultContentLanguage: zh-CN
disableKinds: [taxonomy, term, RSS]
enableRobotsTXT: true
googleAnalytics: G-DVB8ZD276Q

params:
  description: Project Trans 非正式笔记

author:
  name: Project Trans
  url: https://project-trans.org
  email: admin@project-trans.org

social:
  twitter: MtFwiki
  telegram: MtFwiki

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true

languages:
  zh-CN:
    languageCode: zh-CN
    languageName: Chinese
    weight: 1
