baseURL: https://blog.mtf.wiki
title: MtF.wiki 非正式笔记
theme: mtfwiki-blog
copyright: '&copy; $YEAR$ <https://MtF.wiki>'

hasCJKLanguage: true
defaultContentLanguage: zh-CN
disableKinds: [taxonomy, term, RSS]
enableRobotsTXT: true
googleAnalytics: G-DVB8ZD276Q

params:
  description: MtF.wiki 非正式笔记

author:
  name: MtF.wiki
  url: https://mtf.wiki
  email: hi@mtf.wiki

social:
  twitter: MtFwiki
  telegram: MtFwiki

markup:
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
