name: Publish Site

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    branches:
      - main
    paths-ignore:
      - .github
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-22.04
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - run: npm ci
      - run: hugo --minify --buildFuture --cleanDestinationDir
      - run: npx wrangler pages publish public --project-name mtfwiki-blog --branch main
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
